env:
  browser: true
  es6: true
  es2021: true
  jquery: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: latest
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  curly:
    - error
    - all
  no-undef:
    - error
  no-unused-vars: ["error", { "vars": "local" }]
