---
root: true

settings:

env:
  es6: true
  browser: true

globals:

parserOptions:
  ecmaVersion: 8

rules:
  semi: [error, always]
  no-undef: error
  no-unused-vars: warn
    vars: local

  # add culry braces all the time
  # https://eslint.org/docs/rules/curly
  curly: [error, all] # airbnb default: [error, multi-line]
