version: '3.9'
services:
    flashchord-php-apache:
        build: .
        image: php:8.1.9-apache
        volumes:
            - ./:/var/www/html/
        container_name: flashchord-php-apache
        ports:
            - 80:80
