on:
  push:
    branches:
      - develop

name: 🚀 Deploy website to DEV.flashchord.com on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.6
      with:
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server: ${{ secrets.ftp_server }}
        port: 22
        local_path: './*'
        remote_path: '/public_html/'
        sftp_only: true
        rsyncArgs: '--exclude=.git --exclude=.github --exclude=.eslintrc.yml --exclude=.gitattributes --exclude=.gitignore --exclude=collateral --exclude=CHANGELOG.md --exclude=CODE_OF_CONDUCT.md --exclude=CONTRIBUTING.md --exclude=docker-compose.yml --exclude=Dockerfile --exclude=LICENSE.md --exclude=lint.sh --exclude=package-lock.json --exclude=package.json --exclude=README.md --exclude=server'
